[package]
name = "boilerplate_template"
version = "1.0.0"
authors = []

[addresses]
module_addr = "0x9e5cccd94f60191a189438d153c0dbf2386be5b45895183a27a2709e18343869"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
